---
image: ubuntu:20.04

stages:
  - test
  - build
  - release
  - deploy

.mr_trigger:
  only:
    refs:
      - merge_requests

.mr_and_release_trigger:
  only:
    refs:
      - master
      - merge_requests
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/

.release_trigger:
  only:
    refs:
      - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/

.deploy_trigger:
  only:
    refs:
      - tags

test-py3.7:
  extends: .mr_and_release_trigger
  stage: test
  image: python:3.7-slim
  variables:
    APP_VERSION: test
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest -v
  coverage: '/TOTAL.*\s+(\d+%)$/'

test-py3.8:
  extends: .mr_and_release_trigger
  stage: test
  image: python:3.8-slim
  variables:
    APP_VERSION: test
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest -v
  coverage: '/TOTAL.*\s+(\d+%)$/'

test-py3.9:
  extends: .mr_and_release_trigger
  stage: test
  image: python:3.9-slim
  variables:
    APP_VERSION: test
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest -v
  coverage: '/TOTAL.*\s+(\d+%)$/'

test-py3.10:
  extends: .mr_and_release_trigger
  stage: test
  image: python:3.10-slim
  variables:
    APP_VERSION: test
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest -v
  coverage: '/TOTAL.*\s+(\d+%)$/'

release:
  extends: .release_trigger
  stage: release
  image: node:16
  before_script:
    - |
      npm install semantic-release \
      conventional-changelog-conventionalcommits \
      @semantic-release/gitlab \
      @semantic-release/git \
      @semantic-release/release-notes-generator \
      @semantic-release/exec \
      @semantic-release/changelog -D
  script:
    - npx semantic-release

.deploy_base_job:
  extends: .deploy_trigger
  image: ubuntu:20.04
  when: manual
  script:
    - echo "deploy tasks go here"
