name: release-dockerhub

on:
  release:
    types:
      - released

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.6.1
      - name: Configure poetry
        shell: bash
        run: python -m poetry config virtualenvs.in-project true
      - name: Show poetry version
        run: poetry --version
      - name: Build wheel
        run: poetry build --format wheel
      - uses: actions/upload-artifact@v3
        with:
          name: nectl.wheel
          path: dist/

  docker-build-push:
    needs: [build-wheel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: nectl.wheel
          path: docker/dist/
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          tags: |
            nectl/nectl:latest
            nectl/nectl:${{ github.event.release.tag_name }}
          push: true
