name: tests
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - .github/workflows/tests.yaml
      - nectl/**/*.py
      - tests/**/*.py
      - poetry.lock
  push:
    branches:
      - main
    paths:
      - .github/workflows/tests.yaml
      - nectl/**/*.py
      - tests/**/*.py
      - poetry.lock

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Poetry
        shell: bash
        run: pip install poetry
      - name: Configure poetry
        shell: bash
        run: python -m poetry config virtualenvs.in-project true
      - name: Show poetry version
        run: poetry --version
      - name: Install dependencies
        run: poetry install
      - name: Test with pytest
        run: poetry run pytest -v

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python Poetry
        shell: bash
        run: pip install poetry
      - name: Configure poetry
        shell: bash
        run: python -m poetry config virtualenvs.in-project true
      - name: Show poetry version
        run: poetry --version
      - name: Install dependencies
        run: poetry install
      - name: Test with pytest
        run: poetry run pytest -v --cov=nectl --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
